### ISSUE TITLE
Scroll Issue on using wire:navigate

### ISSUE THREAD

**Issue by trumpetstech** [thedevdojo/genesis#31] opened 2023-09-08 03:04 UTC
Title: Scroll Issue After Modal Closure When Using wire:navigate on Edit Profile Link

**Description:**
I encountered a scroll-related issue while using the wire:navigate directive on the "Edit Profile" and than opening of the "Delete Account" modal. After closing the modal, the scroll behavior of the body element gets blocked.

**Steps to Reproduce:**

Navigate to the user profile page.
Click on the "Edit Profile" link.
Click on "Delete Account" button to open the modal.
Close the "Delete Account" modal.

**Expected Behavior:**
After closing the "Delete Account" modal, the scroll on the body element should return to its previous state, allowing the user to scroll the page as usual.

**Actual Behavior:**
Upon closing the "Delete Account" modal, the body scroll appears to be blocked, preventing normal page scrolling.

**Additional Information:**

This issue occurs when using the wire:navigate directive on the "Edit Profile" link to trigger the modal.
The issue does not occur when accessing the "Delete Account" modal through other means.
This issue affects the user experience and can be confusing for users trying to navigate the page after closing the modal.

Here is the video preview of the issue : https://www.loom.com/share/b575d4549fe7455485e3b382e233a09c?sid=f4146780-0e96-4473-8e50-56a8719c80cf

**Comment by tnylea** [comment] 2023-09-12 13:53
Hey @trumpetstech

I've tried replicating the issue, but that doesn't seem to be happening on my end. I'm also using Chrome version 116. I've also tried on Firefox and Safari which seem to be working fine for me.

Are you getting a javascript error when this is happening? Here's how the overflow-hidden happens, when the showModal is set to true, it will add an overflow-hidden class on the body. Then when it is closed it will remove that class. Here is the code that's doing that:

```
$watch('showModal', value => {
    if (value) {
        document.body.classList.add('overflow-y-hidden');
        {{ $attributes->has('focusable') ? 'setTimeout(() => firstFocusable().focus(), 100)' : '' }}
    } else {
        document.body.classList.remove('overflow-y-hidden');
    }
})
```

Can you try adding a `console.log('got here')` inside the `else` statement and let me know if you are hitting that.

Thanks for opening the issue and submitting the video. Let me know about the above info and we'll try and get that fixed 😉

**Comment by tnylea** [comment] 2023-09-28 21:41
Closing the issue since there hasn't been a response in awhile.

Feel free to re-open if you are able to replicate it and let me know how to reproduce 🤙

**Closed by tnylea** 2023-09-28 21:41 UTC
